START TRANSACTION;
CREATE TABLE "EvaluationAttachments" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EvaluationId" integer NOT NULL,
    "FileName" text NOT NULL,
    "FilePath" text NOT NULL,
    "FileSize" bigint NOT NULL,
    "ContentType" text NOT NULL,
    "UploadedByUserId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_EvaluationAttachments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EvaluationAttachments_Evaluations_EvaluationId" FOREIGN KEY ("EvaluationId") REFERENCES "Evaluations" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_EvaluationAttachments_Users_UploadedByUserId" FOREIGN KEY ("UploadedByUserId") REFERENCES "Users" ("Id")
);

CREATE INDEX "IX_EvaluationAttachments_EvaluationId" ON "EvaluationAttachments" ("EvaluationId");

CREATE INDEX "IX_EvaluationAttachments_UploadedByUserId" ON "EvaluationAttachments" ("UploadedByUserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260113114225_AddEvaluationAttachments', '9.0.0');

COMMIT;

