#!/usr/bin/env python3
"""Fix all [DE]/[ES] tagged keys - replace Turkish text with proper EN/DE/ES translations"""
import re, os, sys
sys.stdout.reconfigure(encoding='utf-8')

base = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
loc_dir = os.path.join(base, 'Backend', 'SecretCustomer.API', 'App_Data', 'Localization')

# All 355 tagged keys: key -> {en, de, es}
T = {
    # === Account ===
    "Account.MustChangePassword": {"en": "You must change your password after first login or password reset.", "de": "Sie müssen Ihr Passwort nach der ersten Anmeldung oder Passwortzurücksetzung ändern.", "es": "Debe cambiar su contraseña después del primer inicio de sesión o restablecimiento."},
    "Account.PasswordChangeErrorMessage": {"en": "An error occurred while changing password.", "de": "Fehler beim Ändern des Passworts.", "es": "Ocurrió un error al cambiar la contraseña."},
    # === Api ===
    "Api.Assignment.ProjectNotActive": {"en": "Assignment cannot be created because the project is not active.", "de": "Zuweisung kann nicht erstellt werden, da das Projekt nicht aktiv ist.", "es": "No se puede crear la asignación porque el proyecto no está activo."},
    "Api.Evaluation.ProjectNotActive": {"en": "Evaluation cannot be started because the project is not active.", "de": "Bewertung kann nicht gestartet werden, da das Projekt nicht aktiv ist.", "es": "No se puede iniciar la evaluación porque el proyecto no está activo."},
    # === Approval ===
    "Approval.RejectReason": {"en": "Rejection Reason", "de": "Ablehnungsgrund", "es": "Motivo de Rechazo"},
    "Approval.RejectReasonPlaceholder": {"en": "Enter rejection reason...", "de": "Ablehnungsgrund eingeben...", "es": "Ingrese el motivo de rechazo..."},
    # === Assignment ===
    "Assignment.AddPeriodHint": {"en": "To add a period", "de": "Um einen Zeitraum hinzuzufügen", "es": "Para agregar un período"},
    "Assignment.AllPersons": {"en": "All Persons", "de": "Alle Personen", "es": "Todas las Personas"},
    "Assignment.AllProjects": {"en": "All Projects", "de": "Alle Projekte", "es": "Todos los Proyectos"},
    "Assignment.AllStatuses": {"en": "All Statuses", "de": "Alle Status", "es": "Todos los Estados"},
    "Assignment.AssignedPerson": {"en": "Assigned Person", "de": "Zugewiesene Person", "es": "Persona Asignada"},
    "Assignment.AssigneePerson": {"en": "Person to Assign", "de": "Zuzuweisende Person", "es": "Persona a Asignar"},
    "Assignment.CancelConfirm": {"en": "Are you sure you want to cancel this assignment?", "de": "Möchten Sie diese Zuweisung wirklich stornieren?", "es": "¿Está seguro de que desea cancelar esta asignación?"},
    "Assignment.CancelProcessError": {"en": "An error occurred while canceling the assignment.", "de": "Fehler beim Stornieren der Zuweisung.", "es": "Ocurrió un error al cancelar la asignación."},
    "Assignment.CancelTitle": {"en": "Cancel Assignment", "de": "Zuweisung stornieren", "es": "Cancelar Asignación"},
    "Assignment.Create": {"en": "Create New Assignment", "de": "Neue Zuweisung erstellen", "es": "Crear Nueva Asignación"},
    "Assignment.DetailLoadError": {"en": "An error occurred while loading details.", "de": "Fehler beim Laden der Details.", "es": "Ocurrió un error al cargar los detalles."},
    "Assignment.DueDateFrom": {"en": "Due Date (From)", "de": "Fälligkeitsdatum (Von)", "es": "Fecha Límite (Desde)"},
    "Assignment.DueDateTo": {"en": "Due Date (To)", "de": "Fälligkeitsdatum (Bis)", "es": "Fecha Límite (Hasta)"},
    "Assignment.Edit": {"en": "Edit Assignment", "de": "Zuweisung bearbeiten", "es": "Editar Asignación"},
    "Assignment.External": {"en": "External", "de": "Extern", "es": "Externo"},
    "Assignment.FilterError": {"en": "An error occurred while filtering assignments.", "de": "Fehler beim Filtern der Zuweisungen.", "es": "Ocurrió un error al filtrar las asignaciones."},
    "Assignment.New": {"en": "New Assignment", "de": "Neue Zuweisung", "es": "Nueva Asignación"},
    "Assignment.NewAssigneeType": {"en": "New Assignee Type", "de": "Neuer Zuweisungstyp", "es": "Nuevo Tipo de Asignado"},
    "Assignment.NewDueDateOptional": {"en": "New Due Date (Optional)", "de": "Neues Fälligkeitsdatum (Optional)", "es": "Nueva Fecha Límite (Opcional)"},
    "Assignment.NoPeriods": {"en": "No periods created yet", "de": "Noch keine Zeiträume erstellt", "es": "Aún no se han creado períodos"},
    "Assignment.NoRecords": {"en": "No assignments found or no results matching your filters.", "de": "Keine Zuweisungen gefunden oder keine Ergebnisse für Ihre Filter.", "es": "No se encontraron asignaciones o no hay resultados para sus filtros."},
    "Assignment.Periods": {"en": "Periods", "de": "Zeiträume", "es": "Períodos"},
    "Assignment.Reassign": {"en": "Reassign", "de": "Neu zuweisen", "es": "Reasignar"},
    "Assignment.ReassignProcessError": {"en": "An error occurred while reassigning.", "de": "Fehler bei der Neuzuweisung.", "es": "Ocurrió un error al reasignar."},
    "Assignment.ReassignReasonPlaceholder": {"en": "Reassignment reason...", "de": "Grund der Neuzuweisung...", "es": "Motivo de reasignación..."},
    "Assignment.ReopenConfirm": {"en": "Are you sure you want to reopen this completed assignment? The evaluation will become editable again.", "de": "Möchten Sie diese abgeschlossene Zuweisung wirklich erneut öffnen? Die Bewertung wird wieder bearbeitbar.", "es": "¿Está seguro de que desea reabrir esta asignación completada? La evaluación será editable nuevamente."},
    "Assignment.ReopenError": {"en": "Reopen failed", "de": "Erneutes Öffnen fehlgeschlagen", "es": "Error al reabrir"},
    "Assignment.ReopenProcessError": {"en": "An error occurred while reopening the assignment.", "de": "Fehler beim erneuten Öffnen der Zuweisung.", "es": "Ocurrió un error al reabrir la asignación."},
    "Assignment.ReopenSuccess": {"en": "Assignment reopened successfully.", "de": "Zuweisung erfolgreich erneut geöffnet.", "es": "Asignación reabierta exitosamente."},
    "Assignment.ReopenTitle": {"en": "Reopen Assignment", "de": "Zuweisung erneut öffnen", "es": "Reabrir Asignación"},
    "Assignment.SelectFirst": {"en": "Please select an assignment first!", "de": "Bitte wählen Sie zuerst eine Zuweisung aus!", "es": "¡Primero seleccione una asignación!"},
    "Assignment.ThisAssignment": {"en": "This assignment", "de": "Diese Zuweisung", "es": "Esta asignación"},
    "Assignment.UpdateDueDate": {"en": "Update Due Date", "de": "Fälligkeitsdatum aktualisieren", "es": "Actualizar Fecha Límite"},
    "Assignment.UpdateDueDateError": {"en": "Failed to update due date", "de": "Fälligkeitsdatum konnte nicht aktualisiert werden", "es": "Error al actualizar la fecha límite"},
    "Assignment.UpdateDueDateProcessError": {"en": "An error occurred while updating the due date.", "de": "Fehler beim Aktualisieren des Fälligkeitsdatums.", "es": "Ocurrió un error al actualizar la fecha límite."},
    "Assignment.UpdateDueDateSuccess": {"en": "Due date updated successfully.", "de": "Fälligkeitsdatum erfolgreich aktualisiert.", "es": "Fecha límite actualizada exitosamente."},
    # === AssignmentType ===
    "AssignmentType.CustomerPersonnel": {"en": "Customer Personnel Evaluation", "de": "Kundenpersonalbewertung", "es": "Evaluación de Personal del Cliente"},
    "AssignmentType.ExternalCustomer": {"en": "External Customer Survey", "de": "Externe Kundenbefragung", "es": "Encuesta de Cliente Externo"},
    "AssignmentType.FieldWorker": {"en": "Field Worker Evaluation", "de": "Außendienstmitarbeiterbewertung", "es": "Evaluación de Trabajador de Campo"},
    "AssignmentType.InternalBranch": {"en": "Internal Branch Evaluation", "de": "Interne Filialbewertung", "es": "Evaluación Interna de Sucursal"},
    "AssignmentType.InternalUser": {"en": "Internal User Evaluation", "de": "Interne Benutzerbewertung", "es": "Evaluación de Usuario Interno"},
    # === Button ===
    "Button.OpenForm": {"en": "Open Form", "de": "Formular öffnen", "es": "Abrir Formulario"},
    "Button.QRCode": {"en": "QR Code", "de": "QR-Code", "es": "Código QR"},
    "Button.Reopen": {"en": "Reopen", "de": "Erneut öffnen", "es": "Reabrir"},
    # === Card ===
    "Card.Red": {"en": "Red Card", "de": "Rote Karte", "es": "Tarjeta Roja"},
    "Card.Yellow": {"en": "Yellow Card", "de": "Gelbe Karte", "es": "Tarjeta Amarilla"},
    # === Checklist ===
    "Checklist.AddSubCriteria": {"en": "Add Sub Criteria", "de": "Unterkriterium hinzufügen", "es": "Agregar Subcriterio"},
    "Checklist.AllOrganizations": {"en": "All Organizations", "de": "Alle Organisationen", "es": "Todas las Organizaciones"},
    "Checklist.General": {"en": "General", "de": "Allgemein", "es": "General"},
    "Checklist.MaxPointsHelp": {"en": "1=Yes/No, 5=Detailed", "de": "1=Ja/Nein, 5=Detailliert", "es": "1=Sí/No, 5=Detallado"},
    "Checklist.MaxTotalPointsHelp": {"en": "Default: 100", "de": "Standard: 100", "es": "Predeterminado: 100"},
    "Checklist.Name": {"en": "Name", "de": "Name", "es": "Nombre"},
    "Checklist.NoQuestionsWarning": {"en": "No questions added yet. Please add at least one question.", "de": "Noch keine Fragen hinzugefügt. Bitte fügen Sie mindestens eine Frage hinzu.", "es": "Aún no se han agregado preguntas. Agregue al menos una pregunta."},
    "Checklist.NoRedCard": {"en": "No red card question defined.", "de": "Keine Rote-Karte-Frage definiert.", "es": "No se definió pregunta de tarjeta roja."},
    "Checklist.NoYellowCard": {"en": "No yellow card question defined.", "de": "Keine Gelbe-Karte-Frage definiert.", "es": "No se definió pregunta de tarjeta amarilla."},
    "Checklist.QuestionSummary": {"en": "Question Summary", "de": "Fragenzusammenfassung", "es": "Resumen de Preguntas"},
    "Checklist.RedCardWeightPoints": {"en": "Red Card Weight", "de": "Rote-Karte-Gewichtung", "es": "Peso de Tarjeta Roja"},
    "Checklist.Required": {"en": "Required", "de": "Erforderlich", "es": "Obligatorio"},
    "Checklist.ScoredQuestions": {"en": "Scored Questions", "de": "Bewertete Fragen", "es": "Preguntas Puntuadas"},
    "Checklist.ScoredWeightPoints": {"en": "Scored Question Weight", "de": "Gewichtung bewerteter Fragen", "es": "Peso de Preguntas Puntuadas"},
    "Checklist.ScoringType": {"en": "Scoring", "de": "Bewertung", "es": "Puntuación"},
    "Checklist.ScoringType.Penalty": {"en": "Penalty", "de": "Strafe", "es": "Penalización"},
    "Checklist.ScoringType.Scored": {"en": "Scored", "de": "Bewertet", "es": "Puntuado"},
    "Checklist.ScoringType.Unscored": {"en": "Unscored", "de": "Nicht bewertet", "es": "Sin Puntuar"},
    "Checklist.SearchPlaceholder": {"en": "Name, description or code...", "de": "Name, Beschreibung oder Code...", "es": "Nombre, descripción o código..."},
    "Checklist.Step2.Questions": {"en": "Questions", "de": "Fragen", "es": "Preguntas"},
    "Checklist.SubCriteria": {"en": "Sub Criteria / Suggestions", "de": "Unterkriterien / Vorschläge", "es": "Subcriterios / Sugerencias"},
    "Checklist.SubCriteriaDescription": {"en": "Sub criteria description", "de": "Beschreibung des Unterkriteriums", "es": "Descripción del subcriterio"},
    "Checklist.SubCriteriaHelp": {"en": "Sub criteria can be selected as reasons for score reduction during evaluation.", "de": "Unterkriterien können bei der Bewertung als Gründe für Punktabzug ausgewählt werden.", "es": "Los subcriterios pueden seleccionarse como razones de reducción de puntuación durante la evaluación."},
    "Checklist.YellowCardWeightPoints": {"en": "Yellow Card Weight", "de": "Gelbe-Karte-Gewichtung", "es": "Peso de Tarjeta Amarilla"},
    # === Common ===
    "Common.Action": {"en": "Action", "de": "Aktion", "es": "Acción"},
    "Common.AddFilter": {"en": "Add Filter", "de": "Filter hinzufügen", "es": "Agregar Filtro"},
    "Common.AllFieldsRequired": {"en": "All fields are required.", "de": "Alle Felder sind erforderlich.", "es": "Todos los campos son obligatorios."},
    "Common.AllSupervisors": {"en": "All Supervisors", "de": "Alle Vorgesetzten", "es": "Todos los Supervisores"},
    "Common.AverageScore": {"en": "Avg. Score", "de": "Durchschn. Punktzahl", "es": "Punt. Prom."},
    "Common.Branch": {"en": "Branch", "de": "Filiale", "es": "Sucursal"},
    "Common.City": {"en": "City", "de": "Stadt", "es": "Ciudad"},
    "Common.ClearAll": {"en": "Clear", "de": "Leeren", "es": "Limpiar"},
    "Common.ClearFilter": {"en": "Clear", "de": "Leeren", "es": "Limpiar"},
    "Common.CreatedDate": {"en": "Created Date", "de": "Erstellungsdatum", "es": "Fecha de Creación"},
    "Common.DateRange": {"en": "Date Range", "de": "Datumsbereich", "es": "Rango de Fechas"},
    "Common.DaysLeft": {"en": "days left", "de": "Tage verbleibend", "es": "días restantes"},
    "Common.DaysPassed": {"en": "days passed", "de": "Tage vergangen", "es": "días transcurridos"},
    "Common.Department": {"en": "Department", "de": "Abteilung", "es": "Departamento"},
    "Common.Evaluation": {"en": "Evaluation", "de": "Bewertung", "es": "Evaluación"},
    "Common.File": {"en": "File", "de": "Datei", "es": "Archivo"},
    "Common.FullNamePlaceholder": {"en": "Full Name", "de": "Vor- und Nachname", "es": "Nombre Completo"},
    "Common.History": {"en": "History", "de": "Verlauf", "es": "Historial"},
    "Common.Important": {"en": "Important", "de": "Wichtig", "es": "Importante"},
    "Common.LinkCopied": {"en": "Link copied", "de": "Link kopiert", "es": "Enlace copiado"},
    "Common.LinkCopyError": {"en": "Failed to copy link", "de": "Link konnte nicht kopiert werden", "es": "Error al copiar el enlace"},
    "Common.Location": {"en": "Location", "de": "Standort", "es": "Ubicación"},
    "Common.NewDueDate": {"en": "New Due Date", "de": "Neues Fälligkeitsdatum", "es": "Nueva Fecha Límite"},
    "Common.News": {"en": "News", "de": "Neuigkeiten", "es": "Noticias"},
    "Common.NoDescription": {"en": "No description", "de": "Keine Beschreibung", "es": "Sin descripción"},
    "Common.NoRecords": {"en": "No records found", "de": "Keine Datensätze gefunden", "es": "No se encontraron registros"},
    "Common.Notes": {"en": "Notes", "de": "Notizen", "es": "Notas"},
    "Common.OpenLink": {"en": "Open Link", "de": "Link öffnen", "es": "Abrir Enlace"},
    "Common.OptionalNotes": {"en": "Optional notes...", "de": "Optionale Notizen...", "es": "Notas opcionales..."},
    "Common.Page": {"en": "Page", "de": "Seite", "es": "Página"},
    "Common.PageSize": {"en": "Page Size", "de": "Seitengröße", "es": "Tamaño de Página"},
    "Common.Password": {"en": "Password", "de": "Passwort", "es": "Contraseña"},
    "Common.PerformedBy": {"en": "Performed By", "de": "Durchgeführt von", "es": "Realizado por"},
    "Common.Processing": {"en": "Processing...", "de": "Wird verarbeitet...", "es": "Procesando..."},
    "Common.Reason": {"en": "Reason", "de": "Grund", "es": "Razón"},
    "Common.Records": {"en": "records", "de": "Datensätze", "es": "registros"},
    "Common.Relations": {"en": "Relations", "de": "Beziehungen", "es": "Relaciones"},
    "Common.Result": {"en": "result", "de": "Ergebnis", "es": "resultado"},
    "Common.SearchPersonnel": {"en": "Search personnel...", "de": "Personal suchen...", "es": "Buscar personal..."},
    "Common.Supervisor": {"en": "Supervisor", "de": "Vorgesetzter", "es": "Supervisor"},
    "Common.Syncing": {"en": "Syncing...", "de": "Wird synchronisiert...", "es": "Sincronizando..."},
    "Common.System": {"en": "System", "de": "System", "es": "Sistema"},
    "Common.Tags": {"en": "Tags", "de": "Tags", "es": "Etiquetas"},
    "Common.TotalRecords": {"en": "Total Records", "de": "Gesamtanzahl", "es": "Total de Registros"},
    "Common.Username": {"en": "Username", "de": "Benutzername", "es": "Nombre de Usuario"},
    "Common.Version": {"en": "Version", "de": "Version", "es": "Versión"},
    "Common.ViewAll": {"en": "View All", "de": "Alle anzeigen", "es": "Ver Todo"},
    # === Customer ===
    "Customer.AddOperator": {"en": "Add Operator", "de": "Mitarbeiter hinzufügen", "es": "Agregar Operador"},
    "Customer.AddOperatorToSupervisor": {"en": "Supervisor:", "de": "Vorgesetzter:", "es": "Supervisor:"},
    "Customer.AddSupervisorOrManager": {"en": "Add Manager/Supervisor", "de": "Manager/Vorgesetzten hinzufügen", "es": "Agregar Gerente/Supervisor"},
    "Customer.Description": {"en": "Description", "de": "Beschreibung", "es": "Descripción"},
    "Customer.EditOrganization": {"en": "Edit Organization", "de": "Organisation bearbeiten", "es": "Editar Organización"},
    "Customer.HasTeamMembers": {"en": " has team members below. Please select a delegate to take over these members.", "de": " hat Teammitglieder. Bitte wählen Sie einen Stellvertreter.", "es": " tiene miembros de equipo. Seleccione un delegado."},
    "Customer.IndependentOperatorInfo": {"en": "This operator will be added as independent (no supervisor)", "de": "Dieser Mitarbeiter wird als unabhängig hinzugefügt (ohne Vorgesetzten)", "es": "Este operador será agregado como independiente (sin supervisor)"},
    "Customer.IndependentOperators": {"en": "Independent Operators", "de": "Unabhängige Mitarbeiter", "es": "Operadores Independientes"},
    "Customer.MakeIndependent": {"en": "Make Independent", "de": "Unabhängig machen", "es": "Hacer Independiente"},
    "Customer.MakeIndependentConfirm": {"en": "Are you sure you want to make this personnel independent? They will leave the supervisor but stay in the organization.", "de": "Möchten Sie diesen Mitarbeiter wirklich unabhängig machen? Er verlässt den Vorgesetzten, bleibt aber in der Organisation.", "es": "¿Está seguro de hacer independiente a este personal? Dejará al supervisor pero permanecerá en la organización."},
    "Customer.MakeIndependentError": {"en": "An error occurred while making personnel independent.", "de": "Fehler beim Unabhängigmachen des Mitarbeiters.", "es": "Ocurrió un error al hacer independiente al personal."},
    "Customer.MakeIndependentSuccess": {"en": "Personnel made independent.", "de": "Mitarbeiter wurde unabhängig gemacht.", "es": "Personal hecho independiente."},
    "Customer.Managers": {"en": "Company Managers", "de": "Unternehmensmanager", "es": "Gerentes de Empresa"},
    "Customer.NewIndependentOperator": {"en": "New Independent Operator", "de": "Neuer unabhängiger Mitarbeiter", "es": "Nuevo Operador Independiente"},
    "Customer.NewOrganization": {"en": "New Organization", "de": "Neue Organisation", "es": "Nueva Organización"},
    "Customer.NewSupervisor": {"en": "New Manager/Supervisor", "de": "Neuer Manager/Vorgesetzter", "es": "Nuevo Gerente/Supervisor"},
    "Customer.NoIndependentOperators": {"en": "No independent operators", "de": "Keine unabhängigen Mitarbeiter", "es": "No hay operadores independientes"},
    "Customer.NoOrganizations": {"en": "No organizations yet", "de": "Noch keine Organisationen", "es": "Aún no hay organizaciones"},
    "Customer.NoPersonnelInOrg": {"en": "No personnel in this organization yet", "de": "Noch kein Personal in dieser Organisation", "es": "Aún no hay personal en esta organización"},
    "Customer.OrNewCreate": {"en": "or Create New", "de": "oder Neu erstellen", "es": "o Crear Nuevo"},
    "Customer.OrgManager": {"en": "Organization Manager", "de": "Organisationsleiter", "es": "Gerente de Organización"},
    "Customer.OrganizationCode": {"en": "Organization Code", "de": "Organisationscode", "es": "Código de Organización"},
    "Customer.OrganizationCodePlaceholder": {"en": "CONC-001", "de": "CONC-001", "es": "CONC-001"},
    "Customer.OrganizationManagement": {"en": "Organization Management", "de": "Organisationsverwaltung", "es": "Gestión de Organizaciones"},
    "Customer.OrganizationName": {"en": "Organization Name", "de": "Organisationsname", "es": "Nombre de Organización"},
    "Customer.OrganizationNamePlaceholder": {"en": "Concentrix, Teleperform etc.", "de": "Concentrix, Teleperform usw.", "es": "Concentrix, Teleperform etc."},
    "Customer.Organizations": {"en": "Organizations", "de": "Organisationen", "es": "Organizaciones"},
    "Customer.OrganizationsBranches": {"en": "Organizations / Branches", "de": "Organisationen / Filialen", "es": "Organizaciones / Sucursales"},
    "Customer.PersonnelStructure": {"en": "Personnel Structure", "de": "Personalstruktur", "es": "Estructura de Personal"},
    "Customer.RemoveFromOrg": {"en": "Remove from Organization", "de": "Aus Organisation entfernen", "es": "Eliminar de la Organización"},
    "Customer.SelectDelegate": {"en": "Select Delegate", "de": "Stellvertreter auswählen", "es": "Seleccionar Delegado"},
    "Customer.SelectFromPool": {"en": "Select from Pool", "de": "Aus Pool auswählen", "es": "Seleccionar del Pool"},
    "Customer.SelectNewSupervisor": {"en": "Select New Supervisor", "de": "Neuen Vorgesetzten auswählen", "es": "Seleccionar Nuevo Supervisor"},
    "Customer.SelectOrganization": {"en": "Select an organization from the left to view personnel", "de": "Wählen Sie links eine Organisation aus, um Personal anzuzeigen", "es": "Seleccione una organización de la izquierda para ver el personal"},
    "Customer.TeamMembersCount": {"en": "Team Members to Transfer", "de": "Zu übertragende Teammitglieder", "es": "Miembros del Equipo a Transferir"},
    "Customer.TransferAndRemove": {"en": "Transfer and Remove", "de": "Übertragen und entfernen", "es": "Transferir y Eliminar"},
    # === CustomerOrganization ===
    "CustomerOrganization.Code": {"en": "Organization Code", "de": "Organisationscode", "es": "Código de Organización"},
    "CustomerOrganization.CreateFirst": {"en": "Create First Organization", "de": "Erste Organisation erstellen", "es": "Crear Primera Organización"},
    "CustomerOrganization.Customers": {"en": "Customers", "de": "Kunden", "es": "Clientes"},
    "CustomerOrganization.Description": {"en": "Description", "de": "Beschreibung", "es": "Descripción"},
    "CustomerOrganization.EditOrganization": {"en": "Edit Organization", "de": "Organisation bearbeiten", "es": "Editar Organización"},
    "CustomerOrganization.List": {"en": "Organizations", "de": "Organisationen", "es": "Organizaciones"},
    "CustomerOrganization.Name": {"en": "Organization Name", "de": "Organisationsname", "es": "Nombre de Organización"},
    "CustomerOrganization.NamePlaceholder": {"en": "Concentrix, Teleperform etc.", "de": "Concentrix, Teleperform usw.", "es": "Concentrix, Teleperform etc."},
    "CustomerOrganization.NewOrganization": {"en": "New Organization", "de": "Neue Organisation", "es": "Nueva Organización"},
    "CustomerOrganization.NewPersonnel": {"en": "New Personnel", "de": "Neues Personal", "es": "Nuevo Personal"},
    "CustomerOrganization.NewPersonnelTitle": {"en": "Add New Personnel", "de": "Neues Personal hinzufügen", "es": "Agregar Nuevo Personal"},
    "CustomerOrganization.NoCustomers": {"en": "No customers found", "de": "Keine Kunden gefunden", "es": "No se encontraron clientes"},
    "CustomerOrganization.NoOrganizations": {"en": "No organizations found for this customer.", "de": "Keine Organisationen für diesen Kunden gefunden.", "es": "No se encontraron organizaciones para este cliente."},
    "CustomerOrganization.Order": {"en": "Order", "de": "Reihenfolge", "es": "Orden"},
    "CustomerOrganization.PasswordHint": {"en": "At least 6 characters", "de": "Mindestens 6 Zeichen", "es": "Al menos 6 caracteres"},
    "CustomerOrganization.PersonnelNoOrgInfo": {"en": "This personnel will be added to the company without any organization assignment. You can assign to an organization later.", "de": "Dieses Personal wird ohne Organisationszuordnung zur Firma hinzugefügt. Sie können es später einer Organisation zuordnen.", "es": "Este personal será agregado a la empresa sin asignación de organización. Puede asignarlo a una organización después."},
    "CustomerOrganization.SelectCustomer": {"en": "Select a customer from the left to view organizations", "de": "Wählen Sie links einen Kunden aus, um Organisationen anzuzeigen", "es": "Seleccione un cliente de la izquierda para ver organizaciones"},
    "CustomerOrganization.Title": {"en": "Customer Organizations", "de": "Kundenorganisationen", "es": "Organizaciones de Clientes"},
    "CustomerOrganization.UsernameHint": {"en": "English letters, numbers and underscore only", "de": "Nur englische Buchstaben, Zahlen und Unterstrich", "es": "Solo letras en inglés, números y guion bajo"},
    # === CustomerPersonnel ===
    "CustomerPersonnel.AllCustomers": {"en": "All Customers", "de": "Alle Kunden", "es": "Todos los Clientes"},
    "CustomerPersonnel.Customer": {"en": "Customer", "de": "Kunde", "es": "Cliente"},
    "CustomerPersonnel.Edit": {"en": "Edit Customer Personnel", "de": "Kundenpersonal bearbeiten", "es": "Editar Personal del Cliente"},
    "CustomerPersonnel.New": {"en": "New Customer Personnel", "de": "Neues Kundenpersonal", "es": "Nuevo Personal del Cliente"},
    "CustomerPersonnel.NoPersonnel": {"en": "No customer personnel found.", "de": "Kein Kundenpersonal gefunden.", "es": "No se encontró personal del cliente."},
    "CustomerPersonnel.SelectCustomer": {"en": "Select Customer...", "de": "Kunde auswählen...", "es": "Seleccionar Cliente..."},
    # === CustomerPortal ===
    "CustomerPortal.Dashboard.OrganizationCount": {"en": "Organization", "de": "Organisation", "es": "Organización"},
    "CustomerPortal.Projects.NoRecords": {"en": "No projects defined for your company.", "de": "Keine Projekte für Ihr Unternehmen definiert.", "es": "No hay proyectos definidos para su empresa."},
    "CustomerPortal.Projects.NotFound": {"en": "No Projects Found", "de": "Keine Projekte gefunden", "es": "No se encontraron Proyectos"},
    # === Dashboard ===
    "Dashboard.AnnouncementsLoadError": {"en": "Failed to load announcements", "de": "Ankündigungen konnten nicht geladen werden", "es": "Error al cargar los anuncios"},
    "Dashboard.Completed": {"en": "Completed", "de": "Abgeschlossen", "es": "Completado"},
    "Dashboard.Count": {"en": "Count", "de": "Anzahl", "es": "Cantidad"},
    "Dashboard.DailyTarget": {"en": "Daily Target", "de": "Tagesziel", "es": "Objetivo Diario"},
    "Dashboard.EvaluationCount": {"en": "Evaluation Count", "de": "Bewertungsanzahl", "es": "Número de Evaluaciones"},
    "Dashboard.MinMax": {"en": "Min/Max", "de": "Min/Max", "es": "Mín/Máx"},
    "Dashboard.MyEvaluations": {"en": "My Evaluations", "de": "Meine Bewertungen", "es": "Mis Evaluaciones"},
    "Dashboard.NoDataToday": {"en": "No evaluations today yet", "de": "Heute noch keine Bewertungen", "es": "Aún no hay evaluaciones hoy"},
    "Dashboard.NoEvaluationsThisMonth": {"en": "No evaluations in this period.", "de": "Keine Bewertungen in diesem Zeitraum.", "es": "No hay evaluaciones en este período."},
    "Dashboard.NoMatchingEvaluations": {"en": "No matching evaluations found.", "de": "Keine passenden Bewertungen gefunden.", "es": "No se encontraron evaluaciones coincidentes."},
    "Dashboard.Period": {"en": "Period", "de": "Zeitraum", "es": "Período"},
    "Dashboard.PeriodTarget": {"en": "Period Target", "de": "Zeitraumziel", "es": "Objetivo del Período"},
    "Dashboard.PersonnelAnalysis": {"en": "Personnel Analysis", "de": "Personalanalyse", "es": "Análisis de Personal"},
    "Dashboard.Remaining": {"en": "Remaining", "de": "Verbleibend", "es": "Restante"},
    "Dashboard.Score": {"en": "Score (%)", "de": "Punktzahl (%)", "es": "Puntuación (%)"},
    "Dashboard.SupervisorAnalysis": {"en": "Supervisor Analysis", "de": "Vorgesetztenanalyse", "es": "Análisis de Supervisores"},
    "Dashboard.Target": {"en": "Target", "de": "Ziel", "es": "Objetivo"},
    "Dashboard.ThisWeek": {"en": "This Week", "de": "Diese Woche", "es": "Esta Semana"},
    "Dashboard.Today": {"en": "Today", "de": "Heute", "es": "Hoy"},
    "Dashboard.TopEvaluatorsMonth": {"en": "Top Evaluators This Month", "de": "Top-Bewerter diesen Monat", "es": "Mejores Evaluadores Este Mes"},
    "Dashboard.TopEvaluatorsToday": {"en": "Top Evaluators Today", "de": "Top-Bewerter heute", "es": "Mejores Evaluadores Hoy"},
    "Dashboard.Total": {"en": "Total", "de": "Gesamt", "es": "Total"},
    "Dashboard.User": {"en": "User", "de": "Benutzer", "es": "Usuario"},
    "Dashboard.WeeklyTrend": {"en": "Last 7 Days", "de": "Letzte 7 Tage", "es": "Últimos 7 Días"},
    # === DateRange (additional) ===
    "DateRange.Last30Days": {"en": "Last 30 Days", "de": "Letzte 30 Tage", "es": "Últimos 30 Días"},
    "DateRange.Last7Days": {"en": "Last 7 Days", "de": "Letzte 7 Tage", "es": "Últimos 7 Días"},
    "DateRange.ThisQuarter": {"en": "This Quarter", "de": "Dieses Quartal", "es": "Este Trimestre"},
    "DateRange.ThisWeek": {"en": "This Week", "de": "Diese Woche", "es": "Esta Semana"},
    "DateRange.Today": {"en": "Today", "de": "Heute", "es": "Hoy"},
    # === DraftRequest ===
    "DraftRequest.DetailLoadError": {"en": "Failed to load request details", "de": "Anfragedetails konnten nicht geladen werden", "es": "Error al cargar los detalles de la solicitud"},
    "DraftRequest.NoEvaluationLinked": {"en": "No evaluation linked to this request.", "de": "Keine Bewertung mit dieser Anfrage verknüpft.", "es": "No hay evaluación vinculada a esta solicitud."},
    # === Evaluation ===
    "Evaluation.Assignee": {"en": "Assignee", "de": "Zugewiesener", "es": "Asignado"},
    "Evaluation.EvaluatedInfo": {"en": "Evaluated Information", "de": "Bewertete Informationen", "es": "Información Evaluada"},
    "Evaluation.Form": {"en": "Evaluation Form", "de": "Bewertungsformular", "es": "Formulario de Evaluación"},
    "Evaluation.GoToForm": {"en": "Go to Evaluation Form", "de": "Zum Bewertungsformular gehen", "es": "Ir al Formulario de Evaluación"},
    "Evaluation.Group": {"en": "Group", "de": "Gruppe", "es": "Grupo"},
    "Evaluation.NewPersonnelFirstNameRequired": {"en": "First name is required for new personnel", "de": "Vorname ist für neues Personal erforderlich", "es": "El nombre es obligatorio para nuevo personal"},
    "Evaluation.NewPersonnelLastNameRequired": {"en": "Last name is required for new personnel", "de": "Nachname ist für neues Personal erforderlich", "es": "El apellido es obligatorio para nuevo personal"},
    "Evaluation.NoPersonnelFound": {"en": "No personnel found", "de": "Kein Personal gefunden", "es": "No se encontró personal"},
    "Evaluation.PeriodOpen": {"en": "Active", "de": "Aktiv", "es": "Activo"},
    "Evaluation.SearchPersonnel": {"en": "Search personnel...", "de": "Personal suchen...", "es": "Buscar personal..."},
    "Evaluation.Supervisor": {"en": "Customer Manager", "de": "Kundenmanager", "es": "Gerente del Cliente"},
    "Evaluation.UniqueLink": {"en": "Form Link", "de": "Formularlink", "es": "Enlace del Formulario"},
    # === Import ===
    "Import.EnterChecklistName": {"en": "Please enter a checklist name.", "de": "Bitte geben Sie einen Checklisten-Namen ein.", "es": "Ingrese un nombre de lista de verificación."},
    # === InternalAssignments ===
    "InternalAssignments.AssignmentsCreated": {"en": "assignments created successfully", "de": "Zuweisungen erfolgreich erstellt", "es": "asignaciones creadas exitosamente"},
    "InternalAssignments.CreateError": {"en": "An error occurred while creating assignments", "de": "Fehler beim Erstellen der Zuweisungen", "es": "Ocurrió un error al crear las asignaciones"},
    "InternalAssignments.DeleteError": {"en": "An error occurred while deleting assignment", "de": "Fehler beim Löschen der Zuweisung", "es": "Ocurrió un error al eliminar la asignación"},
    "InternalAssignments.DeleteSuccess": {"en": "Assignment deleted", "de": "Zuweisung gelöscht", "es": "Asignación eliminada"},
    "InternalAssignments.DetailLoadError": {"en": "An error occurred while loading details", "de": "Fehler beim Laden der Details", "es": "Ocurrió un error al cargar los detalles"},
    "InternalAssignments.FillAllFields": {"en": "Please fill in all required fields", "de": "Bitte füllen Sie alle erforderlichen Felder aus", "es": "Complete todos los campos obligatorios"},
    "InternalAssignments.LoadError": {"en": "An error occurred while loading assignments", "de": "Fehler beim Laden der Zuweisungen", "es": "Ocurrió un error al cargar las asignaciones"},
    "InternalAssignments.ThisAssignment": {"en": "This assignment", "de": "Diese Zuweisung", "es": "Esta asignación"},
    # === Key (test) ===
    "Key.Name": {"en": "Fallback Value", "de": "Fallback-Wert", "es": "Valor de Respaldo"},
    # === Listenings ===
    "Listenings.CallDate": {"en": "Date", "de": "Datum", "es": "Fecha"},
    "Listenings.CallId": {"en": "Call ID", "de": "Anruf-ID", "es": "ID de Llamada"},
    "Listenings.CallTime": {"en": "Time", "de": "Uhrzeit", "es": "Hora"},
    "Listenings.Cards": {"en": "Cards", "de": "Karten", "es": "Tarjetas"},
    "Listenings.Detail": {"en": "Listening Detail", "de": "Anhörungsdetail", "es": "Detalle de Escucha"},
    "Listenings.Duration": {"en": "Duration", "de": "Dauer", "es": "Duración"},
    "Listenings.Evaluator": {"en": "Evaluator", "de": "Bewerter", "es": "Evaluador"},
    "Listenings.NoRecords": {"en": "No records found.", "de": "Keine Datensätze gefunden.", "es": "No se encontraron registros."},
    "Listenings.Period": {"en": "Period", "de": "Zeitraum", "es": "Período"},
    "Listenings.Personnel": {"en": "Representative", "de": "Vertreter", "es": "Representante"},
    "Listenings.Score": {"en": "Score", "de": "Punktzahl", "es": "Puntuación"},
    "Listenings.Supervisor": {"en": "Supervisor", "de": "Vorgesetzter", "es": "Supervisor"},
    "Listenings.Title": {"en": "Listenings", "de": "Anhörungen", "es": "Escuchas"},
    # === Menu ===
    "Menu.AuditLogs": {"en": "System Logs", "de": "Systemprotokolle", "es": "Registros del Sistema"},
    "Menu.Listenings": {"en": "Listenings", "de": "Anhörungen", "es": "Escuchas"},
    # === Message ===
    "Message.FilterError": {"en": "Filter failed", "de": "Filterung fehlgeschlagen", "es": "Error en el filtro"},
    "Message.LinkCopied": {"en": "Link copied!", "de": "Link kopiert!", "es": "¡Enlace copiado!"},
    "Message.LinkCopiedToClipboard": {"en": "Link copied to clipboard!", "de": "Link in Zwischenablage kopiert!", "es": "¡Enlace copiado al portapapeles!"},
    "Message.LinkCopyError": {"en": "An error occurred while copying the link.", "de": "Fehler beim Kopieren des Links.", "es": "Ocurrió un error al copiar el enlace."},
    # === Organization (error/success messages) ===
    "Organization.CreateSuccess": {"en": "Organization created.", "de": "Organisation erstellt.", "es": "Organización creada."},
    "Organization.DeleteConfirm": {"en": "Are you sure you want to delete this organization?", "de": "Möchten Sie diese Organisation wirklich löschen?", "es": "¿Está seguro de que desea eliminar esta organización?"},
    "Organization.DeleteError": {"en": "An error occurred while deleting the organization.", "de": "Fehler beim Löschen der Organisation.", "es": "Ocurrió un error al eliminar la organización."},
    "Organization.DeleteSuccess": {"en": "Organization deleted.", "de": "Organisation gelöscht.", "es": "Organización eliminada."},
    "Organization.LoadError": {"en": "An error occurred while loading organizations.", "de": "Fehler beim Laden der Organisationen.", "es": "Ocurrió un error al cargar las organizaciones."},
    "Organization.NameRequired": {"en": "Organization name is required.", "de": "Organisationsname ist erforderlich.", "es": "El nombre de la organización es obligatorio."},
    "Organization.SaveError": {"en": "An error occurred while saving the organization.", "de": "Fehler beim Speichern der Organisation.", "es": "Ocurrió un error al guardar la organización."},
    "Organization.UpdateSuccess": {"en": "Organization updated.", "de": "Organisation aktualisiert.", "es": "Organización actualizada."},
    # === Password ===
    "Password.MinLength": {"en": "New password must be at least 6 characters.", "de": "Neues Passwort muss mindestens 6 Zeichen haben.", "es": "La nueva contraseña debe tener al menos 6 caracteres."},
    "Password.Mismatch": {"en": "New password and confirmation do not match.", "de": "Neues Passwort und Bestätigung stimmen nicht überein.", "es": "La nueva contraseña y la confirmación no coinciden."},
    "Password.ResetError": {"en": "An error occurred while resetting password:", "de": "Fehler beim Zurücksetzen des Passworts:", "es": "Ocurrió un error al restablecer la contraseña:"},
    "Password.ResetSuccess": {"en": "Password reset successfully.", "de": "Passwort erfolgreich zurückgesetzt.", "es": "Contraseña restablecida exitosamente."},
    # === Period ===
    "Period.Add": {"en": "Add Period", "de": "Zeitraum hinzufügen", "es": "Agregar Período"},
    "Period.CreateError": {"en": "Failed to create period", "de": "Zeitraum konnte nicht erstellt werden", "es": "Error al crear el período"},
    "Period.CreateSuccess": {"en": "Period created successfully.", "de": "Zeitraum erfolgreich erstellt.", "es": "Período creado exitosamente."},
    "Period.DailyTarget": {"en": "Daily Target", "de": "Tagesziel", "es": "Objetivo Diario"},
    "Period.DailyTargetHint": {"en": "Number of evaluations to be done daily", "de": "Anzahl der täglich durchzuführenden Bewertungen", "es": "Número de evaluaciones a realizar diariamente"},
    "Period.DateRange": {"en": "Date Range", "de": "Datumsbereich", "es": "Rango de Fechas"},
    "Period.EndDate": {"en": "End Date", "de": "Enddatum", "es": "Fecha Fin"},
    "Period.EndDateRequired": {"en": "End date is required!", "de": "Enddatum ist erforderlich!", "es": "¡La fecha fin es obligatoria!"},
    "Period.InvalidDateRange": {"en": "End date must be after start date!", "de": "Enddatum muss nach dem Startdatum liegen!", "es": "¡La fecha fin debe ser posterior a la fecha de inicio!"},
    "Period.Name": {"en": "Period", "de": "Zeitraum", "es": "Período"},
    "Period.NameHint": {"en": "Enter monthly period name (e.g.: January 2025)", "de": "Monatlichen Zeitraumnamen eingeben (z.B.: Januar 2025)", "es": "Ingrese nombre del período mensual (ej.: Enero 2025)"},
    "Period.NamePlaceholder": {"en": "e.g.: December 2025", "de": "z.B.: Dezember 2025", "es": "ej.: Diciembre 2025"},
    "Period.NameRequired": {"en": "Period name is required!", "de": "Zeitraumname ist erforderlich!", "es": "¡El nombre del período es obligatorio!"},
    "Period.StartDate": {"en": "Start Date", "de": "Startdatum", "es": "Fecha de Inicio"},
    "Period.StartDateRequired": {"en": "Start date is required!", "de": "Startdatum ist erforderlich!", "es": "¡La fecha de inicio es obligatoria!"},
    "Period.TargetRequired": {"en": "Target evaluation count must be at least 1!", "de": "Zielbewertungsanzahl muss mindestens 1 sein!", "es": "¡El número objetivo de evaluaciones debe ser al menos 1!"},
    # === Permission ===
    "Permission.SyncPermissions": {"en": "Sync Permissions", "de": "Berechtigungen synchronisieren", "es": "Sincronizar Permisos"},
    # === Personnel ===
    "Personnel.AssignError": {"en": "An error occurred while assigning personnel.", "de": "Fehler beim Zuweisen des Personals.", "es": "Ocurrió un error al asignar el personal."},
    "Personnel.AssignSuccess": {"en": "Personnel assigned to organization.", "de": "Personal der Organisation zugewiesen.", "es": "Personal asignado a la organización."},
    "Personnel.ChangePassword": {"en": "Change Password", "de": "Passwort ändern", "es": "Cambiar Contraseña"},
    "Personnel.ConfirmPassword": {"en": "Confirm Password", "de": "Passwort bestätigen", "es": "Confirmar Contraseña"},
    "Personnel.CreateError": {"en": "An error occurred while creating manager.", "de": "Fehler beim Erstellen des Managers.", "es": "Ocurrió un error al crear el gerente."},
    "Personnel.LastLogin": {"en": "Last Login", "de": "Letzte Anmeldung", "es": "Último Acceso"},
    "Personnel.ManagerCreated": {"en": "Company manager created.", "de": "Unternehmensmanager erstellt.", "es": "Gerente de empresa creado."},
    "Personnel.NewPassword": {"en": "New Password", "de": "Neues Passwort", "es": "Nueva Contraseña"},
    "Personnel.OperatorAssignSuccess": {"en": "Operator assigned to organization.", "de": "Mitarbeiter der Organisation zugewiesen.", "es": "Operador asignado a la organización."},
    "Personnel.OperatorCreated": {"en": "Operator created and assigned.", "de": "Mitarbeiter erstellt und zugewiesen.", "es": "Operador creado y asignado."},
    "Personnel.Password": {"en": "Password", "de": "Passwort", "es": "Contraseña"},
    "Personnel.RemoveError": {"en": "An error occurred while removing personnel.", "de": "Fehler beim Entfernen des Personals.", "es": "Ocurrió un error al eliminar el personal."},
    "Personnel.RemoveFromOrgConfirm": {"en": "Are you sure you want to remove this personnel from the organization?", "de": "Möchten Sie dieses Personal wirklich aus der Organisation entfernen?", "es": "¿Está seguro de que desea eliminar este personal de la organización?"},
    "Personnel.RemoveSuccess": {"en": "Personnel removed from organization.", "de": "Personal aus Organisation entfernt.", "es": "Personal eliminado de la organización."},
    "Personnel.Role": {"en": "Role", "de": "Rolle", "es": "Rol"},
    "Personnel.RoleRequired": {"en": "Role selection is required.", "de": "Rollenauswahl ist erforderlich.", "es": "La selección de rol es obligatoria."},
    "Personnel.Stats": {"en": "Statistics", "de": "Statistik", "es": "Estadísticas"},
    "Personnel.SupervisorCreated": {"en": "Manager/Supervisor created and assigned.", "de": "Manager/Vorgesetzter erstellt und zugewiesen.", "es": "Gerente/Supervisor creado y asignado."},
    "Personnel.TransferError": {"en": "An error occurred during transfer.", "de": "Fehler bei der Übertragung.", "es": "Ocurrió un error durante la transferencia."},
    "Personnel.TransferSuccess": {"en": "Team members transferred and personnel removed from organization.", "de": "Teammitglieder übertragen und Personal aus Organisation entfernt.", "es": "Miembros transferidos y personal eliminado de la organización."},
    "Personnel.Username": {"en": "Username", "de": "Benutzername", "es": "Nombre de Usuario"},
    # === PersonnelRequest ===
    "PersonnelRequest.NoEvaluationLinked": {"en": "No evaluation linked to this request.", "de": "Keine Bewertung mit dieser Anfrage verknüpft.", "es": "No hay evaluación vinculada a esta solicitud."},
    # === Profile ===
    "Profile.FillAllFields": {"en": "Please fill all fields and ensure passwords match.", "de": "Bitte füllen Sie alle Felder aus und stellen Sie sicher, dass die Passwörter übereinstimmen.", "es": "Complete todos los campos y asegúrese de que las contraseñas coincidan."},
    "Profile.LoadErrorMessage": {"en": "An error occurred while loading profile.", "de": "Fehler beim Laden des Profils.", "es": "Ocurrió un error al cargar el perfil."},
    "Profile.NameRequired": {"en": "First name and last name are required.", "de": "Vor- und Nachname sind erforderlich.", "es": "El nombre y apellido son obligatorios."},
    "Profile.PasswordChangeError": {"en": "An error occurred while changing password.", "de": "Fehler beim Ändern des Passworts.", "es": "Ocurrió un error al cambiar la contraseña."},
    "Profile.PasswordChangeFailed": {"en": "Failed to change password", "de": "Passwortänderung fehlgeschlagen", "es": "Error al cambiar la contraseña"},
    "Profile.PasswordChangeRequired": {"en": "Password Change Required!", "de": "Passwortänderung erforderlich!", "es": "¡Se requiere cambio de contraseña!"},
    "Profile.PasswordChanged": {"en": "Your password has been changed successfully.", "de": "Ihr Passwort wurde erfolgreich geändert.", "es": "Su contraseña ha sido cambiada exitosamente."},
    "Profile.UpdateErrorMessage": {"en": "An error occurred while updating profile.", "de": "Fehler beim Aktualisieren des Profils.", "es": "Ocurrió un error al actualizar el perfil."},
    "Profile.UpdateFailed": {"en": "Failed to update profile", "de": "Profilaktualisierung fehlgeschlagen", "es": "Error al actualizar el perfil"},
    # === Project ===
    "Project.AllCompany": {"en": "Entire Company", "de": "Gesamtes Unternehmen", "es": "Toda la Empresa"},
    "Project.FilesLoadError": {"en": "An error occurred while loading files.", "de": "Fehler beim Laden der Dateien.", "es": "Ocurrió un error al cargar los archivos."},
    "Project.Organization": {"en": "Organization / Branch", "de": "Organisation / Filiale", "es": "Organización / Sucursal"},
    "Project.OrganizationHint": {"en": "If not selected, the project covers the entire company", "de": "Wenn nicht ausgewählt, umfasst das Projekt das gesamte Unternehmen", "es": "Si no se selecciona, el proyecto abarca toda la empresa"},
    # === ProjectStatus ===
    "ProjectStatus.Active": {"en": "Active", "de": "Aktiv", "es": "Activo"},
    "ProjectStatus.Paused": {"en": "Paused", "de": "Pausiert", "es": "Pausado"},
    "ProjectStatus.Planned": {"en": "Planned", "de": "Geplant", "es": "Planificado"},
    # === ProjectType ===
    "ProjectType.CallAuditing": {"en": "Call Auditing", "de": "Anrufprüfung", "es": "Auditoría de Llamadas"},
    "ProjectType.CustomerSatisfaction": {"en": "Customer Satisfaction", "de": "Kundenzufriedenheit", "es": "Satisfacción del Cliente"},
    "ProjectType.MysteryShopping": {"en": "Mystery Shopping", "de": "Testkauf", "es": "Compra Misteriosa"},
    "ProjectType.OnlineSurvey": {"en": "Online Survey", "de": "Online-Umfrage", "es": "Encuesta en Línea"},
    "ProjectType.PhysicalAudit": {"en": "Physical Audit", "de": "Physische Prüfung", "es": "Auditoría Física"},
    "ProjectType.QualityControl": {"en": "Quality Control", "de": "Qualitätskontrolle", "es": "Control de Calidad"},
    "ProjectType.TrainingEvaluation": {"en": "Training Evaluation", "de": "Schulungsbewertung", "es": "Evaluación de Capacitación"},
    # === Question ===
    "Question.GroupNamePlaceholder": {"en": "Group name...", "de": "Gruppenname...", "es": "Nombre del grupo..."},
    # === QuestionType ===
    "QuestionType.Likert": {"en": "Likert Scale", "de": "Likert-Skala", "es": "Escala Likert"},
    "QuestionType.MultipleChoice": {"en": "Multiple Choice", "de": "Multiple Choice", "es": "Opción Múltiple"},
    "QuestionType.Rating": {"en": "Rating Scale", "de": "Bewertungsskala", "es": "Escala de Calificación"},
    "QuestionType.Star": {"en": "Star Rating", "de": "Sternebewertung", "es": "Calificación por Estrellas"},
    "QuestionType.Text": {"en": "Open Text", "de": "Offener Text", "es": "Texto Abierto"},
    "QuestionType.YesNo": {"en": "Yes/No", "de": "Ja/Nein", "es": "Sí/No"},
    # === Report (errors) ===
    "Report.DetailLoadError": {"en": "An error occurred while loading details.", "de": "Fehler beim Laden der Details.", "es": "Ocurrió un error al cargar los detalles."},
    "Report.DetailedExcelDownloadError": {"en": "Failed to download detailed Excel file.", "de": "Detaillierte Excel-Datei konnte nicht heruntergeladen werden.", "es": "Error al descargar el archivo Excel detallado."},
    "Report.ExcelDownloadError": {"en": "Failed to download Excel file.", "de": "Excel-Datei konnte nicht heruntergeladen werden.", "es": "Error al descargar el archivo Excel."},
    "Report.ExcelExportError": {"en": "Excel export failed", "de": "Excel-Export fehlgeschlagen", "es": "Error en la exportación Excel"},
    "Report.LoadErrorMessage": {"en": "An error occurred while loading data.", "de": "Fehler beim Laden der Daten.", "es": "Ocurrió un error al cargar los datos."},
    # === Role ===
    "Role.CustomerPersonnel": {"en": "Customer Representative", "de": "Kundenvertreter", "es": "Representante del Cliente"},
    # === User ===
    "User.EmailExists": {"en": "This email address is already in use.", "de": "Diese E-Mail-Adresse wird bereits verwendet.", "es": "Esta dirección de correo ya está en uso."},
    "User.FieldWorker": {"en": "Field Worker", "de": "Außendienstmitarbeiter", "es": "Trabajador de Campo"},
    "User.Phone": {"en": "Phone", "de": "Telefon", "es": "Teléfono"},
    "User.QualitySpecialist": {"en": "Quality Specialist", "de": "Qualitätsspezialist", "es": "Especialista en Calidad"},
    "User.SystemUsers": {"en": "System Users", "de": "Systembenutzer", "es": "Usuarios del Sistema"},
    "User.UsernameExists": {"en": "This username is already in use.", "de": "Dieser Benutzername wird bereits verwendet.", "es": "Este nombre de usuario ya está en uso."},
    "User.UsernameInvalid": {"en": "Username can only contain English letters, numbers, underscore, period and hyphen. Spaces and special characters are not allowed.", "de": "Benutzername darf nur englische Buchstaben, Zahlen, Unterstrich, Punkt und Bindestrich enthalten. Leerzeichen und Sonderzeichen sind nicht erlaubt.", "es": "El nombre de usuario solo puede contener letras en inglés, números, guion bajo, punto y guion. No se permiten espacios ni caracteres especiales."},
    # === Validation ===
    "Validation.CustomerRequired": {"en": "Customer selection is required.", "de": "Kundenauswahl ist erforderlich.", "es": "La selección de cliente es obligatoria."},
    "Validation.PasswordMinLength": {"en": "New password must be at least 6 characters.", "de": "Neues Passwort muss mindestens 6 Zeichen haben.", "es": "La nueva contraseña debe tener al menos 6 caracteres."},
}

# Process each language file
for lang in ['en', 'de', 'es']:
    xml_name = f'resources.{lang}.xml'
    xml_path = os.path.join(loc_dir, xml_name)
    with open(xml_path, 'r', encoding='utf-8') as f:
        content = f.read()

    updated = 0
    not_found = 0
    for key, trans in T.items():
        if lang not in trans:
            continue
        value = trans[lang]
        safe_value = value.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;').replace('"', '&quot;')

        pattern = f'(<LocaleResource Name="{re.escape(key)}">\\s*<Value>)[^<]*(</Value>)'
        new_content = re.sub(pattern, lambda m: m.group(1) + safe_value + m.group(2), content, count=1)
        if new_content != content:
            content = new_content
            updated += 1
        else:
            not_found += 1

    with open(xml_path, 'w', encoding='utf-8') as f:
        f.write(content)

    total = len([k for k, t in T.items() if lang in t])
    print(f'{xml_name}: Updated {updated}/{total} keys ({not_found} not found)')

print('\nDone!')
