using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace SecretCustomer.Data.Migrations
{
    /// <inheritdoc />
    public partial class AddEmailTemplateToProject : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // EmailTemplates tablosu oluştur (eğer yoksa)
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS ""EmailTemplates"" (
                    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                    ""Name"" text NOT NULL,
                    ""Description"" text,
                    ""Subject"" text NOT NULL,
                    ""Body"" text NOT NULL,
                    ""TemplateTypeId"" integer NOT NULL DEFAULT 1,
                    ""IsActive"" boolean NOT NULL DEFAULT true,
                    ""IsDefault"" boolean NOT NULL DEFAULT false,
                    ""CustomerId"" integer,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    ""UpdatedAt"" timestamp with time zone,
                    ""CreatedBy"" text,
                    ""UpdatedBy"" text,
                    ""IsDeleted"" boolean NOT NULL DEFAULT false,
                    CONSTRAINT ""PK_EmailTemplates"" PRIMARY KEY (""Id""),
                    CONSTRAINT ""FK_EmailTemplates_Customers_CustomerId"" FOREIGN KEY (""CustomerId"") REFERENCES ""Customers"" (""Id"")
                );

                CREATE INDEX IF NOT EXISTS ""IX_EmailTemplates_CustomerId"" ON ""EmailTemplates"" (""CustomerId"");
            ");

            // SurveyIdentityTypeId kolonu ekle (eğer yoksa)
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Projects' AND column_name = 'SurveyIdentityTypeId') THEN
                        ALTER TABLE ""Projects"" ADD ""SurveyIdentityTypeId"" integer NOT NULL DEFAULT 1;
                    END IF;
                END $$;
            ");

            // EmailTemplateId kolonu ekle (eğer yoksa) - yukarıda oluşturulmuş olabilir
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Projects' AND column_name = 'EmailTemplateId') THEN
                        ALTER TABLE ""Projects"" ADD ""EmailTemplateId"" integer;
                    END IF;
                END $$;
            ");

            // ReminderEmailTemplateId kolonu ekle (eğer yoksa)
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Projects' AND column_name = 'ReminderEmailTemplateId') THEN
                        ALTER TABLE ""Projects"" ADD ""ReminderEmailTemplateId"" integer;
                    END IF;
                END $$;
            ");

            // Index'ler (eğer yoksa)
            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_Projects_EmailTemplateId"" ON ""Projects"" (""EmailTemplateId"");
                CREATE INDEX IF NOT EXISTS ""IX_Projects_ReminderEmailTemplateId"" ON ""Projects"" (""ReminderEmailTemplateId"");
            ");

            // SendReminderEmails kolonu ekle (eğer yoksa)
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Projects' AND column_name = 'SendReminderEmails') THEN
                        ALTER TABLE ""Projects"" ADD ""SendReminderEmails"" boolean NOT NULL DEFAULT false;
                    END IF;
                END $$;
            ");

            // ReminderDaysBeforeEnd kolonu ekle (eğer yoksa)
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Projects' AND column_name = 'ReminderDaysBeforeEnd') THEN
                        ALTER TABLE ""Projects"" ADD ""ReminderDaysBeforeEnd"" integer;
                    END IF;
                END $$;
            ");

            // Foreign Key'ler (eğer yoksa)
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Projects_EmailTemplates_EmailTemplateId') THEN
                        ALTER TABLE ""Projects"" ADD CONSTRAINT ""FK_Projects_EmailTemplates_EmailTemplateId""
                            FOREIGN KEY (""EmailTemplateId"") REFERENCES ""EmailTemplates"" (""Id"");
                    END IF;
                END $$;
            ");

            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Projects_EmailTemplates_ReminderEmailTemplateId') THEN
                        ALTER TABLE ""Projects"" ADD CONSTRAINT ""FK_Projects_EmailTemplates_ReminderEmailTemplateId""
                            FOREIGN KEY (""ReminderEmailTemplateId"") REFERENCES ""EmailTemplates"" (""Id"");
                    END IF;
                END $$;
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                ALTER TABLE ""Projects"" DROP CONSTRAINT IF EXISTS ""FK_Projects_EmailTemplates_EmailTemplateId"";
                ALTER TABLE ""Projects"" DROP CONSTRAINT IF EXISTS ""FK_Projects_EmailTemplates_ReminderEmailTemplateId"";
                DROP INDEX IF EXISTS ""IX_Projects_EmailTemplateId"";
                DROP INDEX IF EXISTS ""IX_Projects_ReminderEmailTemplateId"";
                ALTER TABLE ""Projects"" DROP COLUMN IF EXISTS ""EmailTemplateId"";
                ALTER TABLE ""Projects"" DROP COLUMN IF EXISTS ""ReminderEmailTemplateId"";
                ALTER TABLE ""Projects"" DROP COLUMN IF EXISTS ""SurveyIdentityTypeId"";
                DROP TABLE IF EXISTS ""EmailTemplates"";
            ");
        }
    }
}
